// Copyright 2017 Masayoshi Takahashi
//
// original copyright:
// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build ignore

package main

// This program generates tables.go:
//	go run maketables.go | gofmt > tables.go

import (
	"bufio"
	"fmt"
	"log"
	"net/http"
	"sort"
	"strings"

	"github.com/takahashim/aozoraconv"
)

type entry struct {
	men, ku, ten int
}

type twochars struct {
	ch1, ch2 int32
}

type UnicodeTbl [65536 * 4]entry
type JisTbl [2][94][94]string

var reverse UnicodeTbl
var mapping JisTbl
var multichars map[twochars]entry

func getTable(url string) {
	for i := range reverse {
		reverse[i].men = -1
		reverse[i].ku = -1
		reverse[i].ten = -1
	}
	res, err := http.Get(url)
	if err != nil {
		log.Fatalf("Get: %v", err)
	}
	defer res.Body.Close()

	scanner := bufio.NewScanner(res.Body)
	for scanner.Scan() {
		var mkey twochars
		s := strings.TrimSpace(scanner.Text())
		if s == "" || s[0] == '#' {
			continue
		}
		m, k, t, uni, uni2 := 0, 0, 0, int32(0), int32(0)

		if err = aozoraconv.ParseLine(s, &m, &k, &t, &uni, &uni2); err != nil {
			log.Fatalf("could not parse %q; %v", s, err)
		}
		if uni2 > 0 {
			mkey = twochars{ch1: uni, ch2: uni2}
		}
		m -= 2
		k -= 32
		t -= 32
		if m < 1 || 2 < m {
			log.Fatalf("JIS code men %d is out of range", m)
		}
		if k < 1 || 94 < k {
			log.Fatalf("JIS code ku %d is out of range", k)
		}
		if t < 1 || 94 < t {
			log.Fatalf("JIS code ten %d is out of range", t)
		}
		e := entry{men: m, ku: k, ten: t}
		if uni2 > 0 {
			mapping[m-1][k-1][t-1] = string([]rune{uni, uni2})
			multichars[mkey] = e
		} else if uni > 0 {
			mapping[m-1][k-1][t-1] = string([]rune{uni})
			if reverse[uni].men == -1 {
				reverse[uni] = e
			} else {
				log.Fatalf("%U is duplicated, %v %v and %v\n%q", uni, uni2, e, reverse[uni], s)
			}
		}
	}
	if err := scanner.Err(); err != nil {
		log.Fatalf("scanner error: %v", err)
	}
}

func main() {
	fmt.Printf("// generated by go run maketables.go; DO NOT EDIT\n\n")
	fmt.Printf("// Package aozoraconv provides Aozora Bunko format encodings (JIS X 0208/Shift_JIS).\n")
	fmt.Printf(`package aozoraconv // import "github.com/aozorahack/aozoraconv"` + "\n\n")

	reverse = UnicodeTbl{}
	mapping = JisTbl{}
	multichars = make(map[twochars]entry)

	url := "http://x0213.org/codetable/jisx0213-2004-std.txt"
	getTable(url)

	fmt.Printf("// jis0213Decode is the decoding table from JIS 0213 code to Unicode.\n// It is defined at %s\n",
		url)
	fmt.Printf("var jis0213Decode = [...][...][...]uint32{\n")
	for _, m1 := range mapping {
		fmt.Printf("\t{\n\t\t")
		for _, m2 := range m1 {
			fmt.Printf("{\n")
			for _, m3 := range m2 {
				if m3 != "" {
					fmt.Printf("\t\t\t%q,\n", m3)
				}
			}
			fmt.Printf("\t\t},")
		}
		fmt.Printf("\n\t},\n")
	}
	fmt.Printf("}\n\n")

	// Any run of at least separation continuous zero entries in the reverse map will
	// be a separate encode table.
	const separation = 1024

	intervals := []interval(nil)
	low, high := -1, -1
	for i, v := range reverse {
		if v.men < 1 {
			continue
		}
		if low < 0 {
			low = i
		} else if i-high >= separation {
			if high >= 0 {
				intervals = append(intervals, interval{low, high})
			}
			low = i
		}
		high = i + 1
	}
	if high >= 0 {
		intervals = append(intervals, interval{low, high})
	}
	sort.Sort(byDecreasingLength(intervals))

	fmt.Printf("const (\n")
	fmt.Printf("\tcodeMask   = 0x7f\n")
	fmt.Printf("\tcodeShift  = 7\n")
	fmt.Printf("\ttableShift = 14\n")
	fmt.Printf(")\n\n")

	fmt.Printf("const numEncodeTables = %d\n\n", len(intervals))
	fmt.Printf("// encodeX are the encoding tables from Unicode to JIS code,\n")
	fmt.Printf("// sorted by decreasing length.\n")
	for i, v := range intervals {
		fmt.Printf("// encode%d: %5d entries for runes in [%6d, %6d).\n", i, v.len(), v.low, v.high)
	}
	fmt.Printf("//\n")
	fmt.Printf("// The high two bits of the value record whether the JIS code comes from the\n")
	fmt.Printf("// JIS X 0213:2004 plane 1 (high bits == 1) or JIS X 0213:2000 plane 2 (high bits == 2).\n")
	fmt.Printf("// The low 14 bits are two 7-bit unsigned integers j1 and j2 that form the\n")
	fmt.Printf("// JIS code (94*j1 + j2) within that table.\n")
	fmt.Printf("\n")

	for i, v := range intervals {
		fmt.Printf("const encode%dLow, encode%dHigh = %d, %d\n\n", i, i, v.low, v.high)
		fmt.Printf("var encode%d = [...]uint16{\n", i)
		for j := v.low; j < v.high; j++ {
			x := reverse[j]
			if x.men == -1 {
				continue
			}
			fmt.Printf("\t%d - %d: %X<<14 | 0x%02X<<7 | 0x%02X,\n",
				j, v.low, x.men, x.ku, x.ten)
		}
		fmt.Printf("}\n\n")
	}
}

// interval is a half-open interval [low, high).
type interval struct {
	low, high int
}

func (i interval) len() int { return i.high - i.low }

// byDecreasingLength sorts intervals by decreasing length.
type byDecreasingLength []interval

func (b byDecreasingLength) Len() int           { return len(b) }
func (b byDecreasingLength) Less(i, j int) bool { return b[i].len() > b[j].len() }
func (b byDecreasingLength) Swap(i, j int)      { b[i], b[j] = b[j], b[i] }
